FROM python:3.11

RUN echo "export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1"  >> ~/.profile
RUN curl -L https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh && \
    chmod +x ./dotnet-install.sh && \
    ./dotnet-install.sh --channel 7.0 --quality ga && \
    ./dotnet-install.sh --channel 6.0 --quality ga && \
    export DOTNET_ROOT=$HOME/.dotnet && \
    echo "export DOTNET_ROOT=$HOME/.dotnet" >> ~/.profile && \
    echo "export PATH=$PATH:$HOME/.dotnet:$HOME/.dotnet/tools" >> ~/.profile

RUN $HOME/.dotnet/dotnet tool install DefaultDocumentation.Console -g

COPY entrypoint.py /entrypoint.py

ENTRYPOINT ["/bin/bash", "-l", "-c", "python3 /entrypoint.py"]