name: CI

on:
  push:
    branches:
      - 'main'


# Run only one workflow per PR or commit
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

# Disable default permissions for all jobs
permissions: { }

env:
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  test-dotnet:
    permissions:
      contents: read # to fetch code (actions/checkout)
    name: Run C# tests
    runs-on: ${{ matrix.runner.agent }}
    strategy:
      matrix:
        runner: [
          { agent: ubuntu-latest },
        ]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.100-preview.2.23157.25'
      - name: Run C# tests
        working-directory: src
        run: |
          dotnet test -l "console;verbosity=normal" --blame --blame-hang-timeout=30s

  build-dotnet:
    permissions:
      contents: read # to fetch code (actions/checkout)
    name: Build C# nugets
    runs-on: windows-latest
    needs: test-dotnet
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Copy LICENSE to src
        run: |
          cp LICENSE src/LICENSE
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.100-preview.2.23157.25'
      - name: Build nugets
        working-directory: src/builds/csharp/nuget
        run: |
          python3 build_nugets.py
      - name: Upload nugets
        uses: actions/upload-artifact@v3
        with:
          name: windows-x64-nugets
          path: |
            src/builds/csharp/nuget/build-result/*.nupkg
          if-no-files-found: error
